### PR TITLE
Added Makefile

### PR DESCRIPTION
**Pull request by tim241**

### CODE REVIEW

**Comment by minexew** [comment]
Have you tried if this works reliably?

IMO, ``make``, being stateless, won't remember that the "patch" target has been executed previously and will try to run it over and over on every build which, will result in a lot of complaints about patches failing to apply. Using some dummy file like `patches_already_applied` could probably solve that.

**Comment by minexew** [comment]
Further nitpick: any side products created by the build (shrine.img) should also be added to .gitignore

**Comment by tim241** [comment]
I tested it multiple times, works for me. pretty well. I'll add such a dummy file.

**Comment by tim241** [comment]
It should work pretty well right now, I also updated the gitignore!

**Comment by minexew** [comment]
Looks good

**Pull request merged**
